class Config:

    staff_dict = {
        'mhanheide': {
            'firstname': 'Marc',
            'surname': 'Hanheide',
            'orcid': '0000-0001-7728-1849',
            'from': None,
            'until': None,
        },
        'tduckett': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'esklar': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'mrai': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'pbosilj': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'mcalisti': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'gdas': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'jgao': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'lguevara': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'smaleki': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'malkhafajiy': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'apolydoros': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'nbellotto': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'pbaxter': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'gcielniak': {
            'firstname': 'Grzegorz',
            'surname': 'Cielniak',
            'orcid': '0000-0002-6299-8465',
            'from': None,
            'until': None,
        },
        'hcuayahuitl': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'chfox': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'sparsons': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'spearson': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'dbochtis': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'rpolvara': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'fdelduchetto': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'aklimchik': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'hharman': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
        'tzied': {
            'firstname': None,
            'surname': None,
            'orcid': None,
            'from': None,
            'until': None,
        },
    }
