name: update-cache

on:
  schedule:
    - cron: "30 2 * * 1"
  push:
    branches:
      - main

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.PAT }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: |
          git config --global user.name 'L-CAS GitHub'
          git config --global user.email 'marc@hanheide.net'
      - run: |
          python3 lcas-bib-export-generator.py
          git add -f *.bib *.rss *.html
          git commit -m "automated commit"
          git push

