name: update-cache

on:
  schedule:
    - cron: "30 2 * * 1"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: |
          git config --global user.name 'L-CAS GitHub'
          git config --global user.email 'marc@hanheide.net'
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python lcas-bib-export-generator.py
      - if: github.event_name != 'pull_request'
        run: |
          git add -f *.bib *.json *.html
          git commit -m "automated commit `date`"
          git push

